### PR TITLE
Update Mathoid to service-template-node v0.1.3

### PR DESCRIPTION
**Pull request by d00rman**
Brings a lot of bug fixes and improvements, yey :)

### CODE REVIEW

**Comment by physikerwelt** [comment]
@d00rman: Do you see an option to fix the integration tests. Disabeling PNG comparison is fine for me.

**Comment by d00rman** [comment]
> Do you see an option to fix the integration tests.

Yeah, that's a rather hard one. Perhaps in the tests use the underlying lib to produce the png, then issue the request to Mathoid and expect the outputs to match literally? It seems the usage of different libs/versions is the underlying problem in image discrepancies.

> Disabeling PNG comparison is fine for me.

We could do that for now and think of a better way in the future as having tests that we know fail doesn't seem to be too useful :)

**Comment by physikerwelt** [comment]
I checked it to the very best of my knowlege. However, I did no do an explicit code review... I expect that the template code already was reviewed in its repository. For the future, it would be nice to deduplicate that code... mathoid implements mwSrvTmpl

**Pull request merged**
